### ISSUE TITLE
When will the code be made public？

### ISSUE THREAD

**Issue by harrylin-hyl** [yangtiming/ImOV3D#1]
Great job! May I ask when the code will be made public？

**Comment by yangtiming** [comment]
Thank you for your support. After the CVPR submission deadline, I plan to release the code before December 1. You’re welcome to let me know which part you’re most interested in. This will help me understand which sections are of the most interest to the community, so I can prioritize them in the release.

**Comment by superYuezhang** [comment]
> Thank you for your support. After the CVPR submission deadline, I plan to release the code before December 1. You’re welcome to let me know which part you’re most interested in. This will help me understand which sections are of the most interest to the community, so I can prioritize them in the release.

I would love to see the detailed Section _3.4 Point Cloud Renderer_ module code, thank you!

**Comment by yangtiming** [comment]
No problem, you can find the part you're concerned about in `./Data_Maker/PointCloudRender`.
